//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToFast.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionIndex
    {
        public int QuestionId { get; set; }
        public int StudentId { get; set; }
        public int TeacherId { get; set; }
        public System.DateTime QuestionTime { get; set; }
        public string Context { get; set; }
        public bool Anonymous { get; set; }
        public bool Checkable { get; set; }
        public bool Deletable { get; set; }
        public int Evaluation { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
